# Generated by Django 2.2.1 on 2019-05-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('image_name', models.CharField(max_length=30)),
                ('image_information', models.TextField(max_length=200)),
                ('photo_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
