# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_auto_20190523_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='profile_photo',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='insta.Image'),
        ),
    ]
