# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_auto_20190523_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='identity',
        ),
    ]
